import plugin from 'tailwindcss/plugin.js';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{html,js,svelte,ts}'],
  // Preserve the approved design's reset while introducing utilities.
  corePlugins: { preflight: false },
  theme: {
    extend: {
      // The reference theme's color scales are retained below. These portfolio
      // tokens are defined in app.css and preserve the approved design.
      colors: {
        portfolio: {
          white: 'var(--white)',
          sky: 'var(--sky)',
          'sky-soft': 'var(--sky-soft)',
          sun: 'var(--sun)',
          ink: 'var(--ink)',
          muted: 'var(--muted)',
          link: 'var(--link)',
          border: 'var(--border)',
        },
      },
      fontFamily: {
        noto: ['Noto Sans', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'monospace'],
      },
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      blue: {
        0: 'rgb(var(--blue_0) / <alpha-value>)',
        50: 'rgb(var(--blue_50) / <alpha-value>)',
        100: 'rgb(var(--blue_100) / <alpha-value>)',
        200: 'rgb(var(--blue_200) / <alpha-value>)',
        300: 'rgb(var(--blue_300) / <alpha-value>)',
        400: 'rgb(var(--blue_400) / <alpha-value>)',
        500: 'rgb(var(--blue_500) / <alpha-value>)',
        600: 'rgb(var(--blue_600) / <alpha-value>)',
        700: 'rgb(var(--blue_700) / <alpha-value>)',
        800: 'rgb(var(--blue_800) / <alpha-value>)',
        900: 'rgb(var(--blue_900) / <alpha-value>)',
        1000: 'rgb(var(--blue_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--blue_500) / <alpha-value>)',
      },
      burgandy: {
        0: 'rgb(var(--burgandy_0) / <alpha-value>)',
        50: 'rgb(var(--burgandy_50) / <alpha-value>)',
        100: 'rgb(var(--burgandy_100) / <alpha-value>)',
        200: 'rgb(var(--burgandy_200) / <alpha-value>)',
        300: 'rgb(var(--burgandy_300) / <alpha-value>)',
        400: 'rgb(var(--burgandy_400) / <alpha-value>)',
        500: 'rgb(var(--burgandy_500) / <alpha-value>)',
        600: 'rgb(var(--burgandy_600) / <alpha-value>)',
        700: 'rgb(var(--burgandy_700) / <alpha-value>)',
        800: 'rgb(var(--burgandy_800) / <alpha-value>)',
        900: 'rgb(var(--burgandy_900) / <alpha-value>)',
        1000: 'rgb(var(--burgandy_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--burgandy_500) / <alpha-value>)',
      },
      cyan: {
        0: 'rgb(var(--cyan_0) / <alpha-value>)',
        50: 'rgb(var(--cyan_50) / <alpha-value>)',
        100: 'rgb(var(--cyan_100) / <alpha-value>)',
        200: 'rgb(var(--cyan_200) / <alpha-value>)',
        300: 'rgb(var(--cyan_300) / <alpha-value>)',
        400: 'rgb(var(--cyan_400) / <alpha-value>)',
        500: 'rgb(var(--cyan_500) / <alpha-value>)',
        600: 'rgb(var(--cyan_600) / <alpha-value>)',
        700: 'rgb(var(--cyan_700) / <alpha-value>)',
        800: 'rgb(var(--cyan_800) / <alpha-value>)',
        900: 'rgb(var(--cyan_900) / <alpha-value>)',
        1000: 'rgb(var(--cyan_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--cyan_500) / <alpha-value>)',
      },
      gray: {
        0: 'rgb(var(--gray_0) / <alpha-value>)',
        50: 'rgb(var(--gray_50) / <alpha-value>)',
        100: 'rgb(var(--gray_100) / <alpha-value>)',
        200: 'rgb(var(--gray_200) / <alpha-value>)',
        300: 'rgb(var(--gray_300) / <alpha-value>)',
        400: 'rgb(var(--gray_400) / <alpha-value>)',
        500: 'rgb(var(--gray_500) / <alpha-value>)',
        600: 'rgb(var(--gray_600) / <alpha-value>)',
        700: 'rgb(var(--gray_700) / <alpha-value>)',
        800: 'rgb(var(--gray_800) / <alpha-value>)',
        900: 'rgb(var(--gray_900) / <alpha-value>)',
        1000: 'rgb(var(--gray_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--gray_500) / <alpha-value>)',
      },
      green: {
        0: 'rgb(var(--green_0) / <alpha-value>)',
        50: 'rgb(var(--green_50) / <alpha-value>)',
        100: 'rgb(var(--green_100) / <alpha-value>)',
        200: 'rgb(var(--green_200) / <alpha-value>)',
        300: 'rgb(var(--green_300) / <alpha-value>)',
        400: 'rgb(var(--green_400) / <alpha-value>)',
        500: 'rgb(var(--green_500) / <alpha-value>)',
        600: 'rgb(var(--green_600) / <alpha-value>)',
        700: 'rgb(var(--green_700) / <alpha-value>)',
        800: 'rgb(var(--green_800) / <alpha-value>)',
        900: 'rgb(var(--green_900) / <alpha-value>)',
        1000: 'rgb(var(--green_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--green_500) / <alpha-value>)',
      },
      indigo: {
        0: 'rgb(var(--indigo_0) / <alpha-value>)',
        50: 'rgb(var(--indigo_50) / <alpha-value>)',
        100: 'rgb(var(--indigo_100) / <alpha-value>)',
        200: 'rgb(var(--indigo_200) / <alpha-value>)',
        300: 'rgb(var(--indigo_300) / <alpha-value>)',
        400: 'rgb(var(--indigo_400) / <alpha-value>)',
        500: 'rgb(var(--indigo_500) / <alpha-value>)',
        600: 'rgb(var(--indigo_600) / <alpha-value>)',
        700: 'rgb(var(--indigo_700) / <alpha-value>)',
        800: 'rgb(var(--indigo_800) / <alpha-value>)',
        900: 'rgb(var(--indigo_900) / <alpha-value>)',
        1000: 'rgb(var(--indigo_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--indigo_500) / <alpha-value>)',
      },
      orange: {
        0: 'rgb(var(--orange_0) / <alpha-value>)',
        50: 'rgb(var(--orange_50) / <alpha-value>)',
        100: 'rgb(var(--orange_100) / <alpha-value>)',
        200: 'rgb(var(--orange_200) / <alpha-value>)',
        300: 'rgb(var(--orange_300) / <alpha-value>)',
        400: 'rgb(var(--orange_400) / <alpha-value>)',
        500: 'rgb(var(--orange_500) / <alpha-value>)',
        600: 'rgb(var(--orange_600) / <alpha-value>)',
        700: 'rgb(var(--orange_700) / <alpha-value>)',
        800: 'rgb(var(--orange_800) / <alpha-value>)',
        900: 'rgb(var(--orange_900) / <alpha-value>)',
        1000: 'rgb(var(--orange_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--orange_500) / <alpha-value>)',
      },
      pink: {
        0: 'rgb(var(--pink_0) / <alpha-value>)',
        50: 'rgb(var(--pink_50) / <alpha-value>)',
        100: 'rgb(var(--pink_100) / <alpha-value>)',
        200: 'rgb(var(--pink_200) / <alpha-value>)',
        300: 'rgb(var(--pink_300) / <alpha-value>)',
        400: 'rgb(var(--pink_400) / <alpha-value>)',
        500: 'rgb(var(--pink_500) / <alpha-value>)',
        600: 'rgb(var(--pink_600) / <alpha-value>)',
        700: 'rgb(var(--pink_700) / <alpha-value>)',
        800: 'rgb(var(--pink_800) / <alpha-value>)',
        900: 'rgb(var(--pink_900) / <alpha-value>)',
        1000: 'rgb(var(--pink_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--pink_500) / <alpha-value>)',
      },
      purple: {
        0: 'rgb(var(--purple_0) / <alpha-value>)',
        50: 'rgb(var(--purple_50) / <alpha-value>)',
        100: 'rgb(var(--purple_100) / <alpha-value>)',
        200: 'rgb(var(--purple_200) / <alpha-value>)',
        300: 'rgb(var(--purple_300) / <alpha-value>)',
        400: 'rgb(var(--purple_400) / <alpha-value>)',
        500: 'rgb(var(--purple_500) / <alpha-value>)',
        600: 'rgb(var(--purple_600) / <alpha-value>)',
        700: 'rgb(var(--purple_700) / <alpha-value>)',
        800: 'rgb(var(--purple_800) / <alpha-value>)',
        900: 'rgb(var(--purple_900) / <alpha-value>)',
        1000: 'rgb(var(--purple_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--purple_500) / <alpha-value>)',
      },
      red: {
        0: 'rgb(var(--red_0) / <alpha-value>)',
        50: 'rgb(var(--red_50) / <alpha-value>)',
        100: 'rgb(var(--red_100) / <alpha-value>)',
        200: 'rgb(var(--red_200) / <alpha-value>)',
        300: 'rgb(var(--red_300) / <alpha-value>)',
        400: 'rgb(var(--red_400) / <alpha-value>)',
        500: 'rgb(var(--red_500) / <alpha-value>)',
        600: 'rgb(var(--red_600) / <alpha-value>)',
        700: 'rgb(var(--red_700) / <alpha-value>)',
        800: 'rgb(var(--red_800) / <alpha-value>)',
        900: 'rgb(var(--red_900) / <alpha-value>)',
        1000: 'rgb(var(--red_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--red_500) / <alpha-value>)',
      },
      teal: {
        0: 'rgb(var(--teal_0) / <alpha-value>)',
        50: 'rgb(var(--teal_50) / <alpha-value>)',
        100: 'rgb(var(--teal_100) / <alpha-value>)',
        200: 'rgb(var(--teal_200) / <alpha-value>)',
        300: 'rgb(var(--teal_300) / <alpha-value>)',
        400: 'rgb(var(--teal_400) / <alpha-value>)',
        500: 'rgb(var(--teal_500) / <alpha-value>)',
        600: 'rgb(var(--teal_600) / <alpha-value>)',
        700: 'rgb(var(--teal_700) / <alpha-value>)',
        800: 'rgb(var(--teal_800) / <alpha-value>)',
        900: 'rgb(var(--teal_900) / <alpha-value>)',
        1000: 'rgb(var(--teal_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--teal_500) / <alpha-value>)',
      },
      yellow: {
        0: 'rgb(var(--yellow_0) / <alpha-value>)',
        50: 'rgb(var(--yellow_50) / <alpha-value>)',
        100: 'rgb(var(--yellow_100) / <alpha-value>)',
        200: 'rgb(var(--yellow_200) / <alpha-value>)',
        300: 'rgb(var(--yellow_300) / <alpha-value>)',
        400: 'rgb(var(--yellow_400) / <alpha-value>)',
        500: 'rgb(var(--yellow_500) / <alpha-value>)',
        600: 'rgb(var(--yellow_600) / <alpha-value>)',
        700: 'rgb(var(--yellow_700) / <alpha-value>)',
        800: 'rgb(var(--yellow_800) / <alpha-value>)',
        900: 'rgb(var(--yellow_900) / <alpha-value>)',
        1000: 'rgb(var(--yellow_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--yellow_500) / <alpha-value>)',
      },
      danger: {
        0: 'rgb(var(--danger_0) / <alpha-value>)',
        50: 'rgb(var(--danger_50) / <alpha-value>)',
        100: 'rgb(var(--danger_100) / <alpha-value>)',
        200: 'rgb(var(--danger_200) / <alpha-value>)',
        300: 'rgb(var(--danger_300) / <alpha-value>)',
        400: 'rgb(var(--danger_400) / <alpha-value>)',
        500: 'rgb(var(--danger_500) / <alpha-value>)',
        600: 'rgb(var(--danger_600) / <alpha-value>)',
        700: 'rgb(var(--danger_700) / <alpha-value>)',
        800: 'rgb(var(--danger_800) / <alpha-value>)',
        900: 'rgb(var(--danger_900) / <alpha-value>)',
        1000: 'rgb(var(--danger_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--danger_500) / <alpha-value>)',
      },
      info: {
        0: 'rgb(var(--info_0) / <alpha-value>)',
        50: 'rgb(var(--info_50) / <alpha-value>)',
        100: 'rgb(var(--info_100) / <alpha-value>)',
        200: 'rgb(var(--info_200) / <alpha-value>)',
        300: 'rgb(var(--info_300) / <alpha-value>)',
        400: 'rgb(var(--info_400) / <alpha-value>)',
        500: 'rgb(var(--info_500) / <alpha-value>)',
        600: 'rgb(var(--info_600) / <alpha-value>)',
        700: 'rgb(var(--info_700) / <alpha-value>)',
        800: 'rgb(var(--info_800) / <alpha-value>)',
        900: 'rgb(var(--info_900) / <alpha-value>)',
        1000: 'rgb(var(--info_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--info_500) / <alpha-value>)',
      },
      primary: {
        0: 'rgb(var(--primary_0) / <alpha-value>)',
        50: 'rgb(var(--primary_50) / <alpha-value>)',
        100: 'rgb(var(--primary_100) / <alpha-value>)',
        200: 'rgb(var(--primary_200) / <alpha-value>)',
        300: 'rgb(var(--primary_300) / <alpha-value>)',
        400: 'rgb(var(--primary_400) / <alpha-value>)',
        500: 'rgb(var(--primary_500) / <alpha-value>)',
        600: 'rgb(var(--primary_600) / <alpha-value>)',
        700: 'rgb(var(--primary_700) / <alpha-value>)',
        800: 'rgb(var(--primary_800) / <alpha-value>)',
        900: 'rgb(var(--primary_900) / <alpha-value>)',
        1000: 'rgb(var(--primary_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--primary_500) / <alpha-value>)',
      },
      secondary: {
        0: 'rgb(var(--secondary_0) / <alpha-value>)',
        50: 'rgb(var(--secondary_50) / <alpha-value>)',
        100: 'rgb(var(--secondary_100) / <alpha-value>)',
        200: 'rgb(var(--secondary_200) / <alpha-value>)',
        300: 'rgb(var(--secondary_300) / <alpha-value>)',
        400: 'rgb(var(--secondary_400) / <alpha-value>)',
        500: 'rgb(var(--secondary_500) / <alpha-value>)',
        600: 'rgb(var(--secondary_600) / <alpha-value>)',
        700: 'rgb(var(--secondary_700) / <alpha-value>)',
        800: 'rgb(var(--secondary_800) / <alpha-value>)',
        900: 'rgb(var(--secondary_900) / <alpha-value>)',
        1000: 'rgb(var(--secondary_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--secondary_500) / <alpha-value>)',
      },
      success: {
        0: 'rgb(var(--success_0) / <alpha-value>)',
        50: 'rgb(var(--success_50) / <alpha-value>)',
        100: 'rgb(var(--success_100) / <alpha-value>)',
        200: 'rgb(var(--success_200) / <alpha-value>)',
        300: 'rgb(var(--success_300) / <alpha-value>)',
        400: 'rgb(var(--success_400) / <alpha-value>)',
        500: 'rgb(var(--success_500) / <alpha-value>)',
        600: 'rgb(var(--success_600) / <alpha-value>)',
        700: 'rgb(var(--success_700) / <alpha-value>)',
        800: 'rgb(var(--success_800) / <alpha-value>)',
        900: 'rgb(var(--success_900) / <alpha-value>)',
        1000: 'rgb(var(--success_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--success_500) / <alpha-value>)',
      },
      warning: {
        0: 'rgb(var(--warning_0) / <alpha-value>)',
        50: 'rgb(var(--warning_50) / <alpha-value>)',
        100: 'rgb(var(--warning_100) / <alpha-value>)',
        200: 'rgb(var(--warning_200) / <alpha-value>)',
        300: 'rgb(var(--warning_300) / <alpha-value>)',
        400: 'rgb(var(--warning_400) / <alpha-value>)',
        500: 'rgb(var(--warning_500) / <alpha-value>)',
        600: 'rgb(var(--warning_600) / <alpha-value>)',
        700: 'rgb(var(--warning_700) / <alpha-value>)',
        800: 'rgb(var(--warning_800) / <alpha-value>)',
        900: 'rgb(var(--warning_900) / <alpha-value>)',
        1000: 'rgb(var(--warning_1000) / <alpha-value>)',
        DEFAULT: 'rgb(var(--warning_500) / <alpha-value>)',
      },
      white: 'rgb(var(--gray_0) / <alpha-value>)',
      dark: 'rgb(var(--gray_900) / <alpha-value>)',
      black: 'rgb(var(--gray_1000) / <alpha-value>)',
      light: 'rgb(var(--gray_100) / <alpha-value>)',
    },
  },
  plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        '.shadow-focus-primary': {
          'box-shadow': '0 0 0 0.2rem rgb(var(--primary_500) / 0.5)',
        },
        '.shadow-focus-primary-light': {
          'box-shadow': '0 0 0 0.2rem rgb(var(--primary_500) / 0.25)',
        },
        '.shadow-focus-danger': {
          'box-shadow': '0 0 0 0.2rem rgb(var(--danger_500) / 0.5)',
        },
        '.shadow-focus-danger-light': {
          'box-shadow': '0 0 0 0.2rem rgb(var(--danger_500) / 0.25)',
        },
        '.shadow-focus-success': {
          'box-shadow': '0 0 0 0.2rem rgb(var(--success_500) / 0.5)',
        },
        '.shadow-focus-success-light': {
          'box-shadow': '0 0 0 0.2rem rgb(var(--success_500) / 0.25)',
        },
        '.header-gradient': {
          background:
            'linear-gradient(-222deg, rgb(var(--header-gradient-start) / 1), rgb(var(--header-gradient-middle) / 1), rgb(var(--header-gradient-end) / 1))',
          'box-shadow': '0 2px 30px 0 rgba(15, 41, 54, 0.3)',
        },
        '.shadow-focus-toggle': {
          'box-shadow':
            '0 0 0 1px rgb(var(--gray_0) / 1), 0 0 0 0.2rem rgb(var(--primary_500) / 0.25)',
        },
      });
    }),
  ],
};
